services:
  db:
    image: postgres:15
    container_name: famchat-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - famchat-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: famchat-api
    volumes:
      - ./db/migrations:/famchat/db/migrations
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - famchat-net

  ui:
    build: 
      context: .
      dockerfile: famchat-ui/Dockerfile
    container_name: famchat-ui
    volumes:
      - ./famchat-ui:/app
      - /app/node_modules
    ports:
      - "8000:8000"
      - "80:80"
    environment:
      - NODE_ENV=development
    networks:
      - famchat-net

networks:
  famchat-net:
    driver: bridge

volumes:
  postgres_data:

